
### ping
GET http://{{host}}/health/ping

### register
POST http://{{host}}/openapi/register
Content-Type: application/json

{
  "username": "fjx1",
  "pwd": "123456"
}

### login
POST http://{{host}}/openapi/login
Content-Type: application/json

{
  "username": "fjx1",
  "pwd": "123456"
}

> {% client.global.set("auth_token", response.body.data.token); %}

### user profile
GET http://{{host}}/openapi/user/profile
X-Token: {{auth_token}}

