### view blog
GET http://{{host}}/openapi/blog?size=10
X-Uid: 1000


### add blog
POST http://{{host}}/openapi/blog
Content-Type: application/json
X-Uid: 1000

{
  "title": "title3",
  "content": "content3"
}

### get blog
GET http://{{host}}/openapi/blog/3
Content-Type: application/json
X-Uid: 1000


### update blog
PUT http://{{host}}/openapi/blog/3
Content-Type: application/json
X-Uid: 1000

{
  "title": "title3-1",
  "content": "content3-1"
}

### delete blog
DELETE http://{{host}}/openapi/blog/1
X-Uid: 1000
