### view blog
GET http://{{host}}/openapi/blog?size=10
X-Uid: 1000


### add blog
POST http://{{host}}/openapi/blog
Content-Type: application/json
X-Uid: 1000

{
  "title": "title7",
  "content": "content7"
}

### get blog
GET http://{{host}}/openapi/blog/6
Content-Type: application/json
X-Uid: 1000


### update blog
PUT http://{{host}}/openapi/blog/4
Content-Type: application/json
X-Uid: 1000

{
  "title": "title4-3",
  "content": "content4-3"
}

### delete blog
DELETE http://{{host}}/openapi/blog/1
X-Uid: 1000
