### view blog
GET http://{{host}}/openapi/blog?size=10
X-Uid: 1000


### add blog
POST http://{{host}}/openapi/blog
Content-Type: application/json
X-Uid: 1000

{
  "title": "title11",
  "content": "content11"
}

### get blog
GET http://{{host}}/openapi/blog/11
Content-Type: application/json
X-Uid: 1000


### update blog
PUT http://{{host}}/openapi/blog/11
Content-Type: application/json
X-Uid: 1000

{
  "title": "title11-1",
  "content": "content11-1"
}

### delete blog
DELETE http://{{host}}/openapi/blog/11
X-Uid: 1000
