name: go-web-app
env: dev
server:
  host: "0.0.0.0"
  port: 8080
  template:
    - "template"
    - "html"
  access: "./logs/access.log"

mysql:
  default:
    username: app
    password: 1234

redis:
  default:

kafka:
  default:

